# Generated by Django 4.2.23 on 2025-08-20 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle_group', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField(max_length=300)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('num_of_logged_workouts', models.IntegerField()),
                ('uid', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('num_of_sets', models.IntegerField()),
                ('total_reps', models.IntegerField()),
                ('max_weight', models.IntegerField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('is_complete', models.BooleanField()),
                ('muscle_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplefitapi.musclegroup')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplefitapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplefitapi.description')),
                ('workout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplefitapi.workout')),
            ],
        ),
        migrations.AddField(
            model_name='description',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplefitapi.user'),
        ),
    ]
