# Generated by Django 4.2.23 on 2025-08-20 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simplefitapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_tag', to='simplefitapi.user'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='muscle_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_log', to='simplefitapi.musclegroup'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_log', to='simplefitapi.user'),
        ),
        migrations.AlterField(
            model_name='workoutdescription',
            name='description_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_description', to='simplefitapi.description'),
        ),
        migrations.AlterField(
            model_name='workoutdescription',
            name='workout_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_description', to='simplefitapi.workout'),
        ),
    ]
