# Generated by Django 4.2.23 on 2025-09-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplefitapi', '0002_alter_description_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='user_id',
        ),
        migrations.AddField(
            model_name='description',
            name='uid',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='uid',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
    ]
