# Generated by Django 4.2.23 on 2025-09-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplefitapi', '0003_remove_description_user_id_remove_workout_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='descriptions',
            field=models.ManyToManyField(related_name='workout_log', through='simplefitapi.WorkoutDescription', to='simplefitapi.description'),
        ),
    ]
